@port = 3010

GET http://localhost:{{port}}/v1 HTTP/1.1

###

# @name addRoom
POST http://localhost:{{port}}/v1/room HTTP/1.1
content-type: application/json

{
    "name": "test place",
    "x": 2,
    "y": 15,
    "z": 1
}

###

# @name updateRoom
PATCH http://localhost:{{port}}/v1/room/{{addRoom.response.body._id}} HTTP/1.1
content-type: application/json

{
    "monsters": [
        {
            "id": "99",
            "name": "ERROR LIST DATA",
            "num": 15
        }
    ]
}

###

# @name addFloor
POST http://localhost:{{port}}/v1/floor HTTP/1.1
content-type: application/json

{
    "name": "test floor",
    "bindZ": 94,
    "open": true,
    "boss": [
        {
            "id": "69",
            "name": "boss",
            "num": 10
        }
    ],
    "nextFloorId": "96"
}

### 

# @name updateFloor
PATCH http://localhost:{{port}}/v1/floor/{{addFloor.response.body._id}} HTTP/1.1
content-type: application/json

{
    "name": "test",
    "open": false,
    "nextFloorId": "35",
    "bindZ": 13,
    "boss": [
        {
            "id": "8",
            "name": "PASS DATA",
            "num": 68
        }
    ]
}
