db:
  port: 27017
  host: '127.0.0.1'
  name: 'database-test'

server:
  port: 3000

cors: ## cors package 使用的对象属性
  origin: true ## 使用请求中携带的 Origin
  methods: ['GET', 'POST', 'DELETE', 'PATCH', 'PUT']
